задание 1. резиновый макет
KuleshovArtem/admin-panel pull request #1
Opened 2021-09-19 11:01 UTC by KuleshovArtem

2021-09-25 15:44 UTC, Muslik approved these changes
Все ок

2021-09-25 15:44 UTC, Muslik commented on admin-panel-project/style.css
> +.table__footer{
Можно объединить одинаковые стили:
.class1,
.class2 {
  ...
}

2021-10-04 13:06 UTC, baryshkov requested changes
есть замечания

2021-10-04 13:06 UTC, baryshkov commented on admin-panel-project/index.html
> +</head>
![Screenshot 2021-10-04 at 15 59 45](https://user-images.githubusercontent.com/35310783/135856295-34737bcd-1748-47fa-a865-e2e29191816c.png)
на мобиле верстка не работает (нужен кое-какой мета тег)

2021-10-04 13:06 UTC, baryshkov commented on admin-panel-project/style.css
> +    border: 2px solid #A8A8FF ;
цвета неплохо бы вынести в переменную

2021-10-07 20:13 UTC, KuleshovArtem commented on admin-panel-project/index.html
> +</head>
Добавил мета теги

2021-10-07 20:14 UTC, KuleshovArtem commented on admin-panel-project/style.css
> +    border: 2px solid #A8A8FF ;
вывел цвета в переменные

2021-10-07 20:16 UTC, KuleshovArtem commented on admin-panel-project/style.css
> +.table__footer{
не совсем понял что нужно сделать?

2022-01-31 22:24 UTC, merged